trim is too aggressive, right trim is better
sbt/website pull request #397
Opened 2017-07-21 15:31 UTC by JustinPihony

The leading space is needed if you actually have arguments.

2017-07-21 20:05 UTC, eed3si9n requested changes

2017-07-21 20:05 UTC, eed3si9n commented on src/reference/04-Howto/20-Howto-Sequencing/04-Howto-Dynamic-Input-Task.md
> +\* Note that some tasks (ie. `testOnly`) will fail with trailing spaces, so a right trim (`.replaceAll("\\s+$", "")`) of the string built for `toTask` might be needed to handle empty `args`.\
$ sign needs to be escaped to `\$` in Pamflet.

2017-07-22 02:03 UTC, JustinPihony commented on src/reference/04-Howto/20-Howto-Sequencing/04-Howto-Dynamic-Input-Task.md
> +\* Note that some tasks (ie. `testOnly`) will fail with trailing spaces, so a right trim (`.replaceAll("\\s+$", "")`) of the string built for `toTask` might be needed to handle empty `args`.\
Fixed

2017-07-22 02:16 UTC, eed3si9n approved these changes

2017-07-22 02:17 UTC, merged