Japanese translation of 03-Howto-Generating-Files
sbt/website pull request #689
Opened 2018-06-12 05:49 UTC by saint1991

- add a Japanese translation of 03-Howto-Generating-Files

2018-06-12 05:52 UTC, saint1991 commented on src/reference/ja/04-Howto/03-Howto-Generating-Files.md
> +(For efficiency, you would only want to generate sources when necessary and not every run.)
この一文だけこの位置に入っている意図がうまく解釈できておりません。
暫定として(位置は変えていますが)上述のコメントに記載した訳を入れておりますが、訳案をいただけると幸いです。

2018-06-12 05:52 UTC, saint1991 commented on src/reference/ja/04-Howto/03-Howto-Generating-Files.md
> +(このようにしておくと、main のコンパイル時に test のソースコードを生成しなくなり、効率的になる。)
下のコメントで述べている文の訳を暫定的にここに入れています。

2018-06-12 20:31 UTC, eed3si9n requested changes

2018-06-12 20:31 UTC, eed3si9n commented on src/reference/ja/04-Howto/03-Howto-Generating-Files.md
> +(For efficiency, you would only want to generate sources when necessary and not every run.)
あくまで僕の読みですが、多分この文は後から誰かが付け加えたもので多分 `Compile` とか `Test` とか関係無いと思います。ただ、アドバイスとしては非常に重要な点なので残しておくべきだと思いますが、分かりやすいように原文もちょっと変えたほうがいいですね。

訳案: **注意**: ビルドの効率のために、`sourceGenerators` 内では呼ばれる毎にソース生成を行うのではなく、`sbt.Tracked.{ inputChanged, outputChanged }` など用いて、必ず入力値に基づいたキャッシングを行うべきである。

2018-06-13 03:26 UTC, saint1991 commented on src/reference/ja/04-Howto/03-Howto-Generating-Files.md
> +(For efficiency, you would only want to generate sources when necessary and not every run.)
ありがとうございます。
いただいた訳案を元に原文の方も含めて修正してみます!

2018-06-13 05:01 UTC, saint1991 commented on src/reference/04-Howto/03-Howto-Generating-Files.md
> +**NOTE:** You should cache generated sources for efficiency to avoid regenerating them in every build.
いただいた訳案を元に原文も修正しました。
和 => 英はあまり自信がないです...

2018-06-13 05:06 UTC, eed3si9n commented on src/reference/04-Howto/03-Howto-Generating-Files.md
> +**NOTE:** You should cache generated sources for efficiency to avoid regenerating them in every build.
原文: ビルドを効率化するために、 `sourceGenerators` では、呼び出しの度にソースの生成を行うのではなく、`sbt.Tracked.{ inputChanged, outputChanged }` などを用いて、必ず入力値に基づいたキャッシングを行うべきである。
訳案: For the efficiency of the build, `sourceGenerators` should avoid regenerating source files upon each call, and cache based on the input values using `sbt.Tracked.{ inputChanged, outputChanged }` etc instead.

2018-06-13 06:34 UTC, saint1991 commented on src/reference/04-Howto/03-Howto-Generating-Files.md
> +**NOTE:** You should cache generated sources for efficiency to avoid regenerating them in every build.
ありがとうございます! お手数おかけしました...

2018-06-13 08:08 UTC, saint1991 commented
すみません、TravisでPDFの生成に失敗している件をまずは調査します...

2018-06-23 05:14 UTC, saint1991 commented
途中に空白文字が入ってしまっていた問題を修正いたしました。
お手隙きの際にお願いします。

2018-06-23 09:27 UTC, eed3si9n approved these changes

2018-06-23 09:27 UTC, merged