Indicate filename suffix for created file.
sbt/website pull request #698
Opened 2018-07-06 04:29 UTC by blakkan

Instructions indicate to create a file, but don't indicate a filename to use.

2018-07-06 04:29 UTC, lightbend-cla-validator commented
Hi @blakkan,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2018-07-09 04:11 UTC, eed3si9n requested changes
My original description was:

> Create a file named `src/main/scala/example/Hello.scala` using an editor:

then it got changed to 

```diff
-Create a file named `src/main/scala/example/Hello.scala` using an editor:
+Leave the previous command running. From a different shell or in your file managed create in the project
+directory the following nested directories: `src/main/scala/example`. Then, create in the `example`
+directory the following file using your favorite editor:
```

I think we should instruct the user to create `Hello.scala`, like:

> Then, create `Hello.scala`  in the `example` directory using your favorite editor as follows:

2018-07-10 19:24 UTC, blakkan reviewed
Any change is OK, as long as it appropriately indicates filename and filename extension (.scala) to create.
BTW, I thought this was rejected, since I hadn't signed the detailed LightBend agreement.

2018-07-10 20:53 UTC, lightbend-cla-validator commented
Hi @blakkan,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2018-07-10 20:53 UTC, eed3si9n approved these changes

2018-07-10 20:54 UTC, eed3si9n commented
Pushed a commit on your branch with the change.

2018-07-10 20:55 UTC, merged