Docs sbt-server cancellation and completion requests
sbt/website pull request #732
Opened 2018-10-12 09:08 UTC by andreaTP

Here I'm adding the requested documentation for sbt-server cancellation and completion functionality.

cc. @eed3si9n

2018-10-12 14:58 UTC, eed3si9n commented
Thanks for this!!

2018-10-12 15:02 UTC, eed3si9n requested changes
Some comments.

2018-10-12 15:02 UTC, eed3si9n commented on src/reference/02-DetailTopics/01-Using-sbt/07-sbt-server.md
> +A `sbt/completion` request can be used to query command line completions for sbt commands.
The term "commands" for most build users might be taken as Command, so it might be better to say:

> A `sbt/completion` request is used to emulate tab completions for sbt shell.

2018-10-12 15:02 UTC, eed3si9n commented on src/reference/02-DetailTopics/01-Using-sbt/07-sbt-server.md
> +This will respond immediatly based on the last available state of Sbt.
s/Sbt/sbt/.

2018-10-12 15:02 UTC, eed3si9n commented on src/reference/02-DetailTopics/01-Using-sbt/07-sbt-server.md
> +A `sbt/completion` request can be used to query command line completions for sbt commands.
Also it might be good to add a note that this feature will be available for 1.3.0+.

2018-10-15 08:10 UTC, andreaTP commented
done and already squashed commits.

2018-10-17 01:19 UTC, eed3si9n approved these changes
Thanks!

2018-10-17 01:20 UTC, merged