Proposing to add imports of sbt.nio._ and sbt.nio.Keys._
sbt/website pull request #837
Opened 2019-10-06 20:17 UTC by bs76

`fileInputs` require `sbt.nio._` and `sbt.nio.Keys._` imports. This is not obvious in the examples, neither mentioned anywhere in the docs

2019-10-06 20:17 UTC, lightbend-cla-validator commented
Hi @bs76,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

2019-10-07 16:42 UTC, eatkins requested changes
Thanks for this change! The imports are not necessary in a build.sbt file which is why they weren't present in the initial version.

I hate to be pedantic, but would you mind rewriting the commit message? Typically the subject should be no more than 50-60 characters and have an active word at the beginning. The body lines should
be no more than 80 characters unless there is a code line that can't be truncated.

It could be:
```
Add missing imports in file tracking documentation

A number of the fields and classes in the sbt.nio package and the
sbt.nio.Keys object were referenced but not imported.
```

2019-10-07 19:55 UTC, bs76 commented
Amended the commit message (I tried my best, but never did `git commit --amend` before) so hope it's ok now.

As for the imports: they are available by default in `build.sbt` but need to be explicitly imported for plugins/clases under `project`. AFAIU multi build projects can not share `taskKey`/`settingKey` from `build.sbt` in subprojects. The imports are not implicitly visible in classes under `project/`. Took me ~30mins to figure out where `fileInputs` are located.

2019-10-07 20:04 UTC, eatkins commented
> As for the imports: they are available by default in build.sbt but need to be explicitly imported for plugins/clases under project. AFAIU multi build projects can not share taskKey/settingKey from build.sbt in subprojects. The imports are not implicitly visible in classes under project/. Took me ~30mins to figure out where fileInputs are located.

Yeah. Sorry about that. I agree it was an oversight to not have the imports. My previous comment was more of an explanation of why there was an oversight not a defense of it.

> Amended the commit message (I tried my best, but never did git commit --amend before) so hope it's ok now.

I don't think that amend really worked correctly. What I would suggest is the following sequence of git commands:
```
git reset origin/develop
git commit -a
# write the new commit message like in https://github.com/sbt/website/pull/837/commits/88aad5d13a60cfceed0fad69a52a7cd5edc6e18d
git push -f github patch-1
# github is a stand-in for whatever your forked branch is called locally and I'm assuming patch-1 is the branch name
```
Then there would just be one commit associated with this PR instead of 3.

What you could have done given the original commit that I'd commented on was:
```
git commit --amend
# rewrite the commit message
git push -f github patch-1
```

2019-10-07 20:17 UTC, bs76 commented
D'oh ! I did not force-push. Fixed ow (I hope)

2019-10-07 20:18 UTC, eatkins approved these changes

2019-10-07 20:18 UTC, eatkins commented
Ok. Great. Thanks again!

2019-10-07 20:19 UTC, bs76 commented
Thank you too, keep the good work going !

2019-10-07 21:16 UTC, merged